[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.0.0",
    "rich-pixels>=3.0.1",
    "textual-serve==1.1.1",
    "textual>=3.1.1",
    "selection>=0.0.21",
]
